# Adapted from https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/blob/master/.travis.yml
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

branches:
  only:
  - /.*/

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment.yml
  # Sacred can't be installed with conda, so install it *after* the conda install
  - pip install sacred
  - python setup.py install
  # Install seq-align
  - git submodule update --init --recursive
  - cd seq-align && make
  # Return to original directory after install
  - cd -
  # Print record of installed packages
  - conda list

script:
  - source activate rationaldesign
  - coverage run --source=scripts/helper -m unittest discover -s tests
  - coverage report -m
  # Test the snakemake workflow with qsub to check jobs are grouped properly
  - KCN_CURRENT_DIR=$(pwd) snakemake --cluster "qsub -q sl -V" --jobs 2 --dryrun --printshellcmds --use-conda
  - KCN_CURRENT_DIR=$(pwd) snakemake --printshellcmds --use-conda datasets/beta/small/100/clust/{training,validation,test}/data_fingerprints.npz
  - python3 setup.py install
  - pip install sacred
  - python3 scripts/training/logistic_regression.py with representation='fingerprints' dataset='beta/small/100/clust' num_folds=2 num_param_sets=2
  - python3 scripts/training/random_forest.py with representation='fingerprints' dataset='beta/small/100/clust' num_folds=2 num_param_sets=2
  - python3 scripts/training/random_forest_single.py with representation='fingerprints' dataset='beta/small/100/clust'
  - python3 scripts/training/neural_network.py with representation='fingerprints' dataset='beta/small/100/clust' epochs=2

env:
  global:
  # Securely saved MOORHEN_USERNAME and MOORHEN_PASSWORD to access mongo database
  - secure: AApAFzChMnqP4hoU2iNRQLyBXoP33euq39uS9CzNXThJcmRkAmKeP6Xobb2UNaZUZofka3rlN4oOnKTmFEeFf4jDUJDfPhggqNOEQqssIoa32Q7fJT7bOizo20vBlaz+jAr373zlDx9H/KfbXSwvpdhffdfEJCAnvFnEqBe/b3HDCZtVCDkaczGMiTD8+JitUNOk9H47/oArYDMd1DRHpUBhO7WVShsAVGKT6Uqkuu+MR0RwEBENrZOP/E++qr93qbpK1CldO+XNr5Pul7/v+htejLgAUYLi/cnxwFt2qMiZNFcYCWGP2J/9CFE20/vL9scCoEBy30NxkkN0Jos4ykF59531btwVk4vLWNtDhkwsM8pjI7HVPxf3R+lJ7sDGeFrT9TlMI/oYC12CyYVgMGB+sACXTr1JcQd6eqM0wQ2/X7qQI7pif6/7L89m7aGCXcNGkEI98L1gxa/psvANMDF0zaelfAA9YsWCIun/ccjVLvtpGD4QygutYA1ZJwtAh44EMDRZNM/XqqpRjaKDPk0C1sYw2y1VY4WpjLwnvBrepVHlalnGhWjOZkylacL1J93FHfsstRyvYVMhnWe+TgFTPpX8+omGAHK3Gu7P17tNPUO9YdCE/PUD7oUZ77eOcK3nV+zsZJw6ioC0NAvAjMchfqw36HpTbJcagWqI2eI=
  - secure: Xk9HcNJxj2q6TI24abUqHTaZsD+wAzfUp/fqGaO0twCDG+bK3SYPhhU1S/bAbXmjiDoFB3NXafzpI/ObFLaBV4oeF8KMCBP25FbcOHPUHkFJn6SYDRdg+rr6G1DXo182gmFeig073bpHKwY/bA/hKluJ8m4hrJ30a52KyOdk5qXaQmLyl/Ad3Gwg0IwFixJq/kWfZPRZzDHgxbb7CzIDLN7ShMJxrfSffLMyg3oRnN9i+jGrTPVfvqWBn1tNmPRLIJXdaabUOHyQuT/owcWDhx5okSEEDR/3Z53FaT6qJlhRAHQkNqCZ+uIpb8U46ABP4L1OHaG2l3E6CtIzZme5gFkj8vRlzwOEIARz5RNJjnIplVE+2lO/uzNsCPwPim9LufzW55Yf8jEDJv0IH7MS3yA5wMpGD7S4gs5c5bOlFKCmlBtbHY7NVoRo4i/gNXopTOUZTnGzSAknNOwB7CZSE2GFKCOheS4PSBP3Lvw3gJn2H6P+QV32OlcAena8iuoqEcUvDRfMC2GjhJfohi/VxwREo+FiDrIcNsXUesn3Dx9j8dJa9MlYubomY726XUY9rILaf32JymVEXQ6aeKgaXAqJ2IEVfxgyrRKaV4e0/2Luk44iHhsHPeCIgxqg6xXFym0ZIUJY3wXiIhIKf07AKkuZA0rG4aFRqu3qbXCtl9k=

after_success:
  - conda install -c conda-forge coveralls
  - coveralls