# Adapted from https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/blob/master/.travis.yml
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

branches:
  only:
  - /.*/

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment.yml

script:
  - source activate rationaldesign
  # Test the snakemake workflow with qsub to check jobs are grouped properly
  - snakemake processed/bound_pairs/fragmented/unique_bound_pairs.csv --cluster "qsub -q s1" --jobs 2 --dryrun
  - snakemake processed/bound_pairs/fragmented/unique_bound_pairs.csv
