# Adapted from https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/blob/master/.travis.yml
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

branches:
  only:
  - /.*/

install:
  - sudo apt-get update
  # Install hammock, first installing the tool p7zip to unpack the zipped file
  - apt-get install p7zip-full
  - wget https://github.com/krejciadam/hammock/releases/download/v1.2.0/Hammock_v_1.2.0.7z
  - ls -l Hammock_v_1.2.0.7z
  - 7z x Hammock_v_1.2.0.7z
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment.yml
  # Install seq-align
  - git submodule update --init --recursive
  - cd seq-align && make
  # Return to original directory after install
  - cd -

script:
  - source activate rationaldesign
  - coverage run -m unittest discover -v
  - coverage report -m
  # Test the snakemake workflow with qsub to check jobs are grouped properly
  - KCN_CURRENT_DIR=$(pwd) snakemake --cluster "qsub -q sl -V" --jobs 2 --dryrun --printshellcmds
  - KCN_CURRENT_DIR=$(pwd) snakemake --printshellcmds
